### ISSUE TITLE
Why choose SOAP Web Service instead of EDIINT AS2?

### ISSUE THREAD

**Issue by dawud-tan** [JaewookByun/epcis#23]
Walmart since october 2002 until april 2014 prefer to use EPCIS AS2 binding instead of SOAP binding, why Oliot has decided to use SOAP Binding?

http://cdn.corporate.walmart.com/5d/8d/897b4bb84a95bb05214bf897cee3/edi-getting-started-guide.pdf

**Comment by JaewookByun** [comment]
Hi, dawud-tan. 

Thank you for your information. 
The main service interface of Oliot EPCIS is REST APIs even though we also support SOAP APIs.
We choose REST due to its convenience, flexibility, and compatibility, and the reason we support SOAP is to provide 'standard' interface. Note: the EPCIS standard requests to implement one of standard interfaces (i.e., SOAP and AS2) so that supporting all interfaces is already out of scope.  Furthermore, making its programming logic for REST and SOAP makes the system not extendable. Thus, SOAP APIs may be less slightly inefficient than the REST ones since SOAP requests are interpreted to the REST calls in our internal logic. 

Anyway, Oliot epcis is open source. Therefore, if you need EDIINT AS2 binding, you can folk the source code and extend it.

Best Regards,
Jaewook Byun
